sonar.projectKey=Peanut-fn_8.2CDevSecOps
sonar.organization=peanut-fn
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.projectName=NodeJS Goof App
sonar.sourceEncoding=UTF-8